const NAMESPACE = 'redux-products';

export const LOAD_PRODUCTS_START = `${NAMESPACE}/LOAD_PRODUCTS_START`;
export const LOAD_PRODUCTS_SUCCESS = `${NAMESPACE}/LOAD_PRODUCTS_SUCCESS`;
export const LOAD_PRODUCTS_ERROR = `${NAMESPACE}/LOAD_PRODUCTS_ERROR`;

export const DELETE_PRODUCT_START = `${NAMESPACE}/DELETE_PRODUCT_START`;
export const DELETE_PRODUCT_SUCCESS = `${NAMESPACE}/DELETE_PRODUCT_SUCCESS`;
export const DELETE_PRODUCT_ERROR = `${NAMESPACE}/DELETE_PRODUCT_ERROR`;

export const ADD_PRODUCT_START = `${NAMESPACE}/ADD_PRODUCT_START`;
export const ADD_PRODUCT_SUCCESS = `${NAMESPACE}/ADD_PRODUCT_SUCCESS`;
export const ADD_PRODUCT_ERROR = `${NAMESPACE}/ADD_PRODUCT_ERROR`;

export const UPDATE_PRODUCT_START = `${NAMESPACE}/UPDATE_PRODUCT_START`;
export const UPDATE_PRODUCT_SUCCESS = `${NAMESPACE}/UPDATE_PRODUCT_SUCCESS`;
export const UPDATE_PRODUCT_ERROR = `${NAMESPACE}/UPDATE_PRODUCT_ERROR`;
