const NAMESPACE = 'redux-orders';

export const LOAD_ORDERS_START = `${NAMESPACE}/LOAD_ORDERS_START`;
export const LOAD_ORDERS_SUCCESS = `${NAMESPACE}/LOAD_ORDERS_SUCCESS`;
export const LOAD_ORDERS_ERROR = `${NAMESPACE}/LOAD_ORDERS_ERROR`;

export const CANCEL_ORDER_START = `${NAMESPACE}/CANCEL_ORDER_START`;
export const CANCEL_ORDER_SUCCESS = `${NAMESPACE}/CANCEL_ORDER_SUCCESS`;
export const CANCEL_ORDER_ERROR = `${NAMESPACE}/CANCEL_ORDER_ERROR`;

export const ADD_ORDER_START = `${NAMESPACE}/ADD_ORDER_START`;
export const ADD_ORDER_SUCCESS = `${NAMESPACE}/ADD_ORDER_SUCCESS`;
export const ADD_ORDER_ERROR = `${NAMESPACE}/ADD_ORDER_ERROR`;

export const UPDATE_ORDER_START = `${NAMESPACE}/UPDATE_ORDER_START`;
export const UPDATE_ORDER_SUCCESS = `${NAMESPACE}/UPDATE_ORDER_SUCCESS`;
export const UPDATE_ORDER_ERROR = `${NAMESPACE}/UPDATE_ORDER_ERROR`;
