const NAMESPACE = 'redux-permissions';

export const LOAD_PERMISSIONS_START = `${NAMESPACE}/LOAD_PERMISSIONS_START`;
export const LOAD_PERMISSIONS_SUCCESS = `${NAMESPACE}/LOAD_PERMISSIONS_SUCCESS`;
export const LOAD_PERMISSIONS_ERROR = `${NAMESPACE}/LOAD_PERMISSIONS_ERROR`;

export const ADD_PERMISSION_START = `${NAMESPACE}/ADD_PERMISSION_START`;
export const ADD_PERMISSION_SUCCESS = `${NAMESPACE}/ADD_PERMISSION_SUCCESS`;
export const ADD_PERMISSION_ERROR = `${NAMESPACE}/ADD_PERMISSION_ERROR`;

export const UPDATE_PERMISSION_START = `${NAMESPACE}/UPDATE_PERMISSION_START`;
export const UPDATE_PERMISSION_SUCCESS = `${NAMESPACE}/UPDATE_PERMISSION_SUCCESS`;
export const UPDATE_PERMISSION_ERROR = `${NAMESPACE}/UPDATE_PERMISSION_ERROR`;
