const NAMESPACE = 'redux-tools';

export const LOAD_TOOLS_START = `${NAMESPACE}/LOAD_TOOLS_START`;
export const LOAD_TOOLS_SUCCESS = `${NAMESPACE}/LOAD_TOOLS_SUCCESS`;
export const LOAD_TOOLS_ERROR = `${NAMESPACE}/LOAD_TOOLS_ERROR`;

export const DELETE_TOOL_START = `${NAMESPACE}/DELETE_TOOL_START`;
export const DELETE_TOOL_SUCCESS = `${NAMESPACE}/DELETE_TOOL_SUCCESS`;
export const DELETE_TOOL_ERROR = `${NAMESPACE}/DELETE_TOOL_ERROR`;

export const ADD_TOOL_START = `${NAMESPACE}/ADD_TOOL_START`;
export const ADD_TOOL_SUCCESS = `${NAMESPACE}/ADD_TOOL_SUCCESS`;
export const ADD_TOOL_ERROR = `${NAMESPACE}/ADD_TOOL_ERROR`;

export const UPDATE_TOOL_START = `${NAMESPACE}/UPDATE_TOOL_START`;
export const UPDATE_TOOL_SUCCESS = `${NAMESPACE}/UPDATE_TOOL_SUCCESS`;
export const UPDATE_TOOL_ERROR = `${NAMESPACE}/UPDATE_TOOL_ERROR`;
