const NAMESPACE = 'redux-manufacturing-plans';

export const LOAD_MANUFACTURING_PLANS_START = `${NAMESPACE}/LOAD_MANUFACTURING_PLANS_START`;
export const LOAD_MANUFACTURING_PLANS_SUCCESS = `${NAMESPACE}/LOAD_MANUFACTURING_PLANS_SUCCESS`;
export const LOAD_MANUFACTURING_PLANS_ERROR = `${NAMESPACE}/LOAD_MANUFACTURING_PLANS_ERROR`;

export const DELETE_MANUFACTURING_PLAN_START = `${NAMESPACE}/DELETE_MANUFACTURING_PLAN_START`;
export const DELETE_MANUFACTURING_PLAN_SUCCESS = `${NAMESPACE}/DELETE_MANUFACTURING_PLAN_SUCCESS`;
export const DELETE_MANUFACTURING_PLAN_ERROR = `${NAMESPACE}/DELETE_MANUFACTURING_PLAN_ERROR`;

export const ADD_MANUFACTURING_PLAN_START = `${NAMESPACE}/ADD_MANUFACTURING_PLAN_START`;
export const ADD_MANUFACTURING_PLAN_SUCCESS = `${NAMESPACE}/ADD_MANUFACTURING_PLAN_SUCCESS`;
export const ADD_MANUFACTURING_PLAN_ERROR = `${NAMESPACE}/ADD_MANUFACTURING_PLAN_ERROR`;

export const UPDATE_MANUFACTURING_PLAN_START = `${NAMESPACE}/UPDATE_MANUFACTURING_PLAN_START`;
export const UPDATE_MANUFACTURING_PLAN_SUCCESS = `${NAMESPACE}/UPDATE_MANUFACTURING_PLAN_SUCCESS`;
export const UPDATE_MANUFACTURING_PLAN_ERROR = `${NAMESPACE}/UPDATE_MANUFACTURING_PLAN_ERROR`;
