const NAMESPACE = 'redux-machines';

export const LOAD_MACHINES_START = `${NAMESPACE}/LOAD_MACHINES_START`;
export const LOAD_MACHINES_SUCCESS = `${NAMESPACE}/LOAD_MACHINES_SUCCESS`;
export const LOAD_MACHINES_ERROR = `${NAMESPACE}/LOAD_MACHINES_ERROR`;

export const DELETE_MACHINE_START = `${NAMESPACE}/DELETE_MACHINE_START`;
export const DELETE_MACHINE_SUCCESS = `${NAMESPACE}/DELETE_MACHINE_SUCCESS`;
export const DELETE_MACHINE_ERROR = `${NAMESPACE}/DELETE_MACHINE_ERROR`;

export const ADD_MACHINE_START = `${NAMESPACE}/ADD_MACHINE_START`;
export const ADD_MACHINE_SUCCESS = `${NAMESPACE}/ADD_MACHINE_SUCCESS`;
export const ADD_MACHINE_ERROR = `${NAMESPACE}/ADD_MACHINE_ERROR`;

export const UPDATE_MACHINE_START = `${NAMESPACE}/UPDATE_MACHINE_START`;
export const UPDATE_MACHINE_SUCCESS = `${NAMESPACE}/UPDATE_MACHINE_SUCCESS`;
export const UPDATE_MACHINE_ERROR = `${NAMESPACE}/UPDATE_MACHINE_ERROR`;
