/* 
 * Master Data Factory (MDF) - API
 *
 * Rest API for MDF Master Data Factory
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using factory.api.client.Client;
using factory.api.client.Api;
using factory.api.client.Model;

namespace factory.api.client.Test
{
    /// <summary>
    ///  Class for testing OperationsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class OperationsApiTests : IDisposable
    {
        private OperationsApi instance;

        public OperationsApiTests()
        {
            instance = new OperationsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OperationsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' OperationsApi
            //Assert.IsType(typeof(OperationsApi), instance, "instance is a OperationsApi");
        }

        
        /// <summary>
        /// Test OperationsDelete
        /// </summary>
        [Fact]
        public void OperationsDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //instance.OperationsDelete(id);
            
        }
        
        /// <summary>
        /// Test OperationsGetOperation
        /// </summary>
        [Fact]
        public void OperationsGetOperationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //instance.OperationsGetOperation(id);
            
        }
        
        /// <summary>
        /// Test OperationsGetOperations
        /// </summary>
        [Fact]
        public void OperationsGetOperationsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? offset = null;
            //int? limit = null;
            //instance.OperationsGetOperations(offset, limit);
            
        }
        
        /// <summary>
        /// Test OperationsPost
        /// </summary>
        [Fact]
        public void OperationsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //InOperationDTO inOperationDTO = null;
            //instance.OperationsPost(inOperationDTO);
            
        }
        
        /// <summary>
        /// Test OperationsPut
        /// </summary>
        [Fact]
        public void OperationsPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //InOperationDTO inOperationDTO = null;
            //instance.OperationsPut(id, inOperationDTO);
            
        }
        
    }

}
