/* 
 * Master Data Factory (MDF) - API
 *
 * Rest API for MDF Master Data Factory
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using factory.api.client.Api;
using factory.api.client.Model;
using factory.api.client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace factory.api.client.Test
{
    /// <summary>
    ///  Class for testing InMachineTypeDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InMachineTypeDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InMachineTypeDTO
        //private InMachineTypeDTO instance;

        public InMachineTypeDTOTests()
        {
            // TODO uncomment below to create an instance of InMachineTypeDTO
            //instance = new InMachineTypeDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InMachineTypeDTO
        /// </summary>
        [Fact]
        public void InMachineTypeDTOInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InMachineTypeDTO
            //Assert.IsInstanceOfType<InMachineTypeDTO> (instance, "variable 'instance' is a InMachineTypeDTO");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Operations'
        /// </summary>
        [Fact]
        public void OperationsTest()
        {
            // TODO unit test for the property 'Operations'
        }

    }

}
