/* 
 * Master Data Factory (MDF) - API
 *
 * Rest API for MDF Master Data Factory
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using factory.api.client.Api;
using factory.api.client.Model;
using factory.api.client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace factory.api.client.Test
{
    /// <summary>
    ///  Class for testing InProductionLineDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InProductionLineDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InProductionLineDTO
        //private InProductionLineDTO instance;

        public InProductionLineDTOTests()
        {
            // TODO uncomment below to create an instance of InProductionLineDTO
            //instance = new InProductionLineDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InProductionLineDTO
        /// </summary>
        [Fact]
        public void InProductionLineDTOInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InProductionLineDTO
            //Assert.IsInstanceOfType<InProductionLineDTO> (instance, "variable 'instance' is a InProductionLineDTO");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Machines'
        /// </summary>
        [Fact]
        public void MachinesTest()
        {
            // TODO unit test for the property 'Machines'
        }

    }

}
