const NAMESPACE = 'redux-production-lines';

export const LOAD_PRODUCTION_LINES_START = `${NAMESPACE}/LOAD_PRODUCTION_LINES_START`;
export const LOAD_PRODUCTION_LINES_SUCCESS = `${NAMESPACE}/LOAD_PRODUCTION_LINES_SUCCESS`;
export const LOAD_PRODUCTION_LINES_ERROR = `${NAMESPACE}/LOAD_PRODUCTION_LINES_ERROR`;

export const DELETE_PRODUCTION_LINE_START = `${NAMESPACE}/DELETE_PRODUCTION_LINE_START`;
export const DELETE_PRODUCTION_LINE_SUCCESS = `${NAMESPACE}/DELETE_PRODUCTION_LINE_SUCCESS`;
export const DELETE_PRODUCTION_LINE_ERROR = `${NAMESPACE}/DELETE_PRODUCTION_LINE_ERROR`;

export const ADD_PRODUCTION_LINE_START = `${NAMESPACE}/ADD_PRODUCTION_LINE_START`;
export const ADD_PRODUCTION_LINE_SUCCESS = `${NAMESPACE}/ADD_PRODUCTION_LINE_SUCCESS`;
export const ADD_PRODUCTION_LINE_ERROR = `${NAMESPACE}/ADD_PRODUCTION_LINE_ERROR`;

export const UPDATE_PRODUCTION_LINE_START = `${NAMESPACE}/UPDATE_PRODUCTION_LINE_START`;
export const UPDATE_PRODUCTION_LINE_SUCCESS = `${NAMESPACE}/UPDATE_PRODUCTION_LINE_SUCCESS`;
export const UPDATE_PRODUCTION_LINE_ERROR = `${NAMESPACE}/UPDATE_PRODUCTION_LINE_ERROR`;
