const NAMESPACE = 'redux-operations';

export const LOAD_OPERATIONS_START = `${NAMESPACE}/LOAD_OPERATIONS_START`;
export const LOAD_OPERATIONS_SUCCESS = `${NAMESPACE}/LOAD_OPERATIONS_SUCCESS`;
export const LOAD_OPERATIONS_ERROR = `${NAMESPACE}/LOAD_OPERATIONS_ERROR`;

export const DELETE_OPERATION_START = `${NAMESPACE}/DELETE_OPERATION_START`;
export const DELETE_OPERATION_SUCCESS = `${NAMESPACE}/DELETE_OPERATION_SUCCESS`;
export const DELETE_OPERATION_ERROR = `${NAMESPACE}/DELETE_OPERATION_ERROR`;

export const ADD_OPERATION_START = `${NAMESPACE}/ADD_OPERATION_START`;
export const ADD_OPERATION_SUCCESS = `${NAMESPACE}/ADD_OPERATION_SUCCESS`;
export const ADD_OPERATION_ERROR = `${NAMESPACE}/ADD_OPERATION_ERROR`;

export const UPDATE_OPERATION_START = `${NAMESPACE}/UPDATE_OPERATION_START`;
export const UPDATE_OPERATION_SUCCESS = `${NAMESPACE}/UPDATE_OPERATION_SUCCESS`;
export const UPDATE_OPERATION_ERROR = `${NAMESPACE}/UPDATE_OPERATION_ERROR`;
