const NAMESPACE = 'redux-machine-types';

export const LOAD_MACHINE_TYPES_START = `${NAMESPACE}/LOAD_MACHINE_TYPES_START`;
export const LOAD_MACHINE_TYPES_SUCCESS = `${NAMESPACE}/LOAD_MACHINE_TYPES_SUCCESS`;
export const LOAD_MACHINE_TYPES_ERROR = `${NAMESPACE}/LOAD_MACHINE_TYPES_ERROR`;

export const DELETE_MACHINE_TYPE_START = `${NAMESPACE}/DELETE_MACHINE_TYPE_START`;
export const DELETE_MACHINE_TYPE_SUCCESS = `${NAMESPACE}/DELETE_MACHINE_TYPE_SUCCESS`;
export const DELETE_MACHINE_TYPE_ERROR = `${NAMESPACE}/DELETE_MACHINE_TYPE_ERROR`;

export const ADD_MACHINE_TYPE_START = `${NAMESPACE}/ADD_MACHINE_TYPE_START`;
export const ADD_MACHINE_TYPE_SUCCESS = `${NAMESPACE}/ADD_MACHINE_TYPE_SUCCESS`;
export const ADD_MACHINE_TYPE_ERROR = `${NAMESPACE}/ADD_MACHINE_TYPE_ERROR`;

export const UPDATE_MACHINE_TYPE_START = `${NAMESPACE}/UPDATE_MACHINE_TYPE_START`;
export const UPDATE_MACHINE_TYPE_SUCCESS = `${NAMESPACE}/UPDATE_MACHINE_TYPE_SUCCESS`;
export const UPDATE_MACHINE_TYPE_ERROR = `${NAMESPACE}/UPDATE_MACHINE_TYPE_ERROR`;
